### ISSUE TITLE
[Suggestion] Publish On CurseForge

### ISSUE THREAD

**Issue by Blueil** [DeadlyMC/QuickCarpet#65]
Publish this mod on CurseForge so sites like aternos can use this mod.

**Comment by Ziadshoura** [comment]
Yes please do this I'm genuinely having a lot of trouble just finding the download link :/

**Comment by Tobs3l** [comment]
that would be really awesome

**Comment by DragonEggBedrockBreaking** [comment]
and also modrinth

**Comment by DragonEggBedrockBreaking** [comment]
> Yes please do this I'm genuinely having a lot of trouble just finding the download link :/

https://github.com/DeadlyMC/QuickCarpet/releases

**Comment by skyrising** [comment]
Modrinth is live (https://modrinth.com/mod/quickcarpet), waiting for approval on CurseForge

**Comment by skyrising** [comment]
CurseForge (https://www.curseforge.com/minecraft/mc-mods/quickcarpet) is also live now
